<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="Constants" Id="{ff96902c-5136-0ae0-1075-e89641639929}" SpecialFunc="None">
    <Declaration><![CDATA[// Contains string constants for working with files
{attribute 'no_explicit_call' := 'Body contains no logic, calling methods only allowed.'}
{attribute 'hide_all_locals'}
PROGRAM Constants
VAR
	_pathSeperators	: FB_PathSeperators;	
	_wildcards	: FB_Wildcards;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="PathSeperators" Id="{79e1fca6-79e7-07e8-052c-4d9c7cd66fd4}">
      <Declaration><![CDATA[// Returns WINDOWS path separator "/"
PROPERTY PathSeperators : REFERENCE TO FB_PathSeperators]]></Declaration>
      <Get Name="Get" Id="{e5c4fede-1050-0288-3d07-af087dead439}">
        <Declaration><![CDATA[
]]></Declaration>
        <Implementation>
          <ST><![CDATA[PathSeperators REF= _pathSeperators;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Wildcards" Id="{205ac2e7-93f7-0748-2d16-c4c53b0f5d9e}">
      <Declaration><![CDATA[PROPERTY Wildcards : REFERENCE TO FB_Wildcards]]></Declaration>
      <Get Name="Get" Id="{1e9a9c22-2a62-021e-0029-6d9c07909dea}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Wildcards REF= _wildcards;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>