<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_SUT_Tests" Id="{ef158edd-0b71-4c2b-ba0c-90e4d3e3af98}" SpecialFunc="None">
    <Declaration><![CDATA[// Subject under test
FUNCTION_BLOCK INTERNAL FB_SUT_Tests EXTENDS FB_TestSuite

// Create instance variables that will be accesible for all tests
VAR
	fbTcpIp	: FB_TcpIpCommControl;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Call your test methods here
THIS^.TestCase1_Test();]]></ST>
    </Implementation>
    <Method Name="TestCase1_Test" Id="{73f655e5-b999-49e6-95f7-1ed302b4d6e5}">
      <Declaration><![CDATA[METHOD PRIVATE TestCase1_Test

(* Instanced variables are VERY useful for writing tests since tests are run in paralel (by default).
By instantiating local variables that are not placed on the same stack as method (values are retained between calls)
you make sure that the SUT is not changed by some other test. *)
VAR_INST
	
END_VAR

// Place temporary variables here
VAR
	
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[// The name of the test, is the same as method name!
TcUnit.TEST('TestCase1_Test');

// Do your assertions here...
AssertTrue(Condition := FALSE, Message := 'Implement tests!');

TcUnit.TEST_FINISHED();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>