<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Logger" Id="{86b60fa4-cbc9-0995-00ad-63ce008210aa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Logger IMPLEMENTS I_Logger
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_fileProperties	: ST_FileProperties;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="FileProperties" Id="{cf4970f1-019f-0d7d-194d-eece40979b6a}">
      <Declaration><![CDATA[PROPERTY FileProperties : REFERENCE TO ST_FileProperties
]]></Declaration>
      <Get Name="Get" Id="{3c4a3446-662e-0dc2-0a1b-1173128bc028}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FileProperties ref= _fileProperties;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{342e182c-81d6-0861-102e-27b46f0e464b}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[_fileProperties := FileProperties;]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="LogError" Id="{0826df63-6e74-08c4-10be-52e84363dcaf}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD LogError
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="LogGeneric" Id="{202b6ae4-7e18-0d99-16d4-423d5f5bfd54}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD LogGeneric
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="LogInfo" Id="{d4bc99de-06e2-0964-11a9-a4a87d9d7009}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD LogInfo
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="LogWarning" Id="{8cb67f2f-1c5a-08cb-193b-66dbde75b5eb}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD LogWarning
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Logger">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.FileProperties.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.FileProperties.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.LogError">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.LogGeneric">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.LogInfo">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.LogWarning">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>