<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_IoLinkChannel_64Byte" Id="{68a380d4-8093-0eca-0d36-be4d6f49b641}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT FB_IoLinkChannel_64Byte
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	Inputs 	AT %I*	: T_IoLink64ByteData;
	Outputs	AT %Q*	: T_IoLink64ByteData;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>