<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FileHelper" Id="{937eb662-c0cd-004b-2265-3a2c8b97ceb1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FileHelper
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CreateFilePath" Id="{9d3e4243-2ab4-033b-34bf-4e54e0f1953b}">
      <Declaration><![CDATA[// Creates file path from the location and file name. Optionally file extension can also be provided, or left empty.
METHOD CreateFilePath : T_MaxString
VAR_INPUT
	fileLocation	: Tc2_System.T_MaxString;	// File location
	fileName		: Tc2_System.T_MaxString;	// Nae of the file
	extension		: STRING;	// File extension
END_VAR

VAR
	stringBuilder	: FB_StringBuilder;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CreateFilePath := stringBuilder
	.AddString(fileLocation)
	.AddString('\')
	.AddString(fileName)
	.AddString(extension)
	.Create();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>